[package]
name = "telegram-client"
version = "0.1.0"
authors = ["fewensa <fewensa@protonmail.com>"]
description = "Telegram client"
homepage = "https://github.com/fewensa/telegram-client"
repository = "https://github.com/fewensa/telegram-client"
license = "MIT"
keywords = ["tdlib", "telegram", "telegram-client", "bindings"]
categories = ["api-bindings"]
include = [
  "Cargo.toml",
  "**/*.rs",
  "**/*.tpl.rs",
  "**/*.tpl.toml",
  "README.md",
  "LICENSE"
]
readme = "README.md"
edition = "2018"

build = "build/build.rs"

[dependencies]

text-reader = "0.2.1"
rstring-builder = "0.1.4"
#toolkit = { git = "https://github.com/fewensa/toolkit" }
toolkit = "0.1.1"

rtdlib = { git = "https://github.com/fewensa/rtdlib" }
#rtdlib = { path = "../rtdlib" }
#rtdlib = "0.1.1"

serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"

daemon = "0.0.8"

slog = "2.4.1"
slog-term = "2.4.0"
lazy_static = "1.3.0"


error-chain-mini = "0.2.0"
error-chain-mini-derive = "0.2.0"


[build-dependencies]

text-reader = "0.2.1"
rstring-builder = "0.1.4"
tera = "0.11.20"

toml = "0.5.1"

serde = "1.0.91"
serde_derive = "1.0.91"

#toolkit = { git = "https://github.com/fewensa/toolkit" }
toolkit = "0.1.1"

