[package]
name = "telegram-client"
version = "0.1.0"
authors = ["fewensa <fewensa@protonmail.com>"]
description = "Telegram client"
homepage = "https://github.com/fewensa/telegram-client"
repository = "https://github.com/fewensa/telegram-client"
license = "MIT"
keywords = ["tdlib", "telegram", "telegram-client", "bindings"]
categories = ["api-bindings"]
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
readme = "README.md"
edition = "2018"

build = "build.rs"

[dependencies]

text-reader = "0.2.1"
rstring-builder = "0.1.4"
toolkit = "0.1.0"

rtdlib = { git = "https://github.com/fewensa/rtdlib" }
#rtdlib = "0.1.1"

serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"

